//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnDoesBroswer.EncryptService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncryptService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Encrypt", ReplyAction="http://tempuri.org/IService/EncryptResponse")]
        string Encrypt(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Encrypt", ReplyAction="http://tempuri.org/IService/EncryptResponse")]
        System.Threading.Tasks.Task<string> EncryptAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decrypt", ReplyAction="http://tempuri.org/IService/DecryptResponse")]
        string Decrypt(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decrypt", ReplyAction="http://tempuri.org/IService/DecryptResponse")]
        System.Threading.Tasks.Task<string> DecryptAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : JohnDoesBroswer.EncryptService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<JohnDoesBroswer.EncryptService.IService>, JohnDoesBroswer.EncryptService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Encrypt(string text) {
            return base.Channel.Encrypt(text);
        }
        
        public System.Threading.Tasks.Task<string> EncryptAsync(string text) {
            return base.Channel.EncryptAsync(text);
        }
        
        public string Decrypt(string text) {
            return base.Channel.Decrypt(text);
        }
        
        public System.Threading.Tasks.Task<string> DecryptAsync(string text) {
            return base.Channel.DecryptAsync(text);
        }
    }
}
